[package]
name = "xdp_iphash_to_cpu_cmdline"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
lqos_bus = { path = "../lqos_bus" }
